### ISSUE TITLE
InvalidDescriptionException: Invalid plugin.yml

### ISSUE THREAD

**Issue by uncovery** [floored1585/SpawnerGuard#1]
[09:41:52] [Server thread/ERROR]: Could not load 'plugins/SpawnerGuard.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
<------>at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
<------>at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-f928e7a-e91aed8]
<------>at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-f928e7a-e91aed8]
<------>at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-f928e7a-e91aed8]
<------>at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-f928e7a-e91aed8]
<------>at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.util.zip.ZipException: error in opening zip file
<------>at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_79]
<------>at java.util.zip.ZipFile.<init>(ZipFile.java:215) ~[?:1.7.0_79]
<------>at java.util.zip.ZipFile.<init>(ZipFile.java:145) ~[?:1.7.0_79]
<------>at java.util.jar.JarFile.<init>(JarFile.java:154) ~[?:1.7.0_79]
<------>at java.util.jar.JarFile.<init>(JarFile.java:118) ~[?:1.7.0_79]
<------>at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-f928e7a-e91aed8]
<------>... 5 more

**Comment by uncovery** [comment]
The plugin crashed on server start

**Comment by floored1585** [comment]
turned out to be a corrupt file!
